//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BugTraceEntities : DbContext
    {
        public BugTraceEntities()
            : base("name=BugTraceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PPM_MessageRecord> PPM_MessageRecord { get; set; }
        public DbSet<PPM_ProblemTraceHis> PPM_ProblemTraceHis { get; set; }
        public DbSet<PPM_ProblemTraceImage> PPM_ProblemTraceImage { get; set; }
        public DbSet<PPM_ProjectInfo> PPM_ProjectInfo { get; set; }
        public DbSet<PPM_ProjectPlan> PPM_ProjectPlan { get; set; }
        public DbSet<PPM_ProjectTeam> PPM_ProjectTeam { get; set; }
        public DbSet<PPM_ShareFile> PPM_ShareFile { get; set; }
        public DbSet<SCM_SaleOrder> SCM_SaleOrder { get; set; }
        public DbSet<SYS_Menu> SYS_Menu { get; set; }
        public DbSet<SYS_Role> SYS_Role { get; set; }
        public DbSet<SYS_SortDict> SYS_SortDict { get; set; }
        public DbSet<SYS_User> SYS_User { get; set; }
        public DbSet<SYS_UserExt> SYS_UserExt { get; set; }
        public DbSet<SYS_Version> SYS_Version { get; set; }
        public DbSet<V_ProjectPlan> V_ProjectPlan { get; set; }
        public DbSet<PPM_ProblemTrace> PPM_ProblemTrace { get; set; }
        public DbSet<SYS_UserRole> SYS_UserRole { get; set; }
    }
}
