//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPM_ProblemTraceImage
    {
        public string ID { get; set; }
        public Nullable<int> ProblemTraceID { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public byte[] ImageFile { get; set; }
        public string ImagePath { get; set; }
        public Nullable<byte> StorageType { get; set; }
    
        public virtual PPM_ProblemTrace PPM_ProblemTrace { get; set; }
    }
}
