//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPM_ProjectTeam
    {
        public string ProjectCode { get; set; }
        public string TeamLeader { get; set; }
        public string TeamMember { get; set; }
        public byte Status { get; set; }
    
        public virtual PPM_ProjectInfo PPM_ProjectInfo { get; set; }
        public virtual SYS_User SYS_User { get; set; }
        public virtual SYS_User SYS_User1 { get; set; }
    }
}
