//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCM_SaleOrder
    {
        public int ID { get; set; }
        public string AgentName { get; set; }
        public string AgentTel { get; set; }
        public string CustomName { get; set; }
        public string CustomTel { get; set; }
        public string CustomAddr { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryType { get; set; }
        public string DeliveryNo { get; set; }
        public string GoodName { get; set; }
        public string GoodSort { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> SumMoney { get; set; }
        public string GiftDesc { get; set; }
        public Nullable<decimal> GiftQty { get; set; }
        public string PayType { get; set; }
        public string PayStatus { get; set; }
        public string Memo { get; set; }
    }
}
