//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_User
    {
        public SYS_User()
        {
            this.PPM_MessageRecord = new HashSet<PPM_MessageRecord>();
            this.PPM_MessageRecord1 = new HashSet<PPM_MessageRecord>();
            this.PPM_ProjectInfo = new HashSet<PPM_ProjectInfo>();
            this.PPM_ProjectPlan = new HashSet<PPM_ProjectPlan>();
            this.PPM_ProjectPlan1 = new HashSet<PPM_ProjectPlan>();
            this.PPM_ProjectTeam = new HashSet<PPM_ProjectTeam>();
            this.PPM_ProjectTeam1 = new HashSet<PPM_ProjectTeam>();
            this.PPM_ShareFile = new HashSet<PPM_ShareFile>();
            this.PPM_ProblemTrace = new HashSet<PPM_ProblemTrace>();
            this.PPM_ProblemTrace1 = new HashSet<PPM_ProblemTrace>();
            this.PPM_ProblemTrace2 = new HashSet<PPM_ProblemTrace>();
            this.PPM_ProblemTrace3 = new HashSet<PPM_ProblemTrace>();
            this.PPM_ProblemTrace4 = new HashSet<PPM_ProblemTrace>();
            this.PPM_ProblemTrace5 = new HashSet<PPM_ProblemTrace>();
        }
    
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string QQ { get; set; }
        public string Tel { get; set; }
        public string DefaultProjectCode { get; set; }
        public string UrlPort { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<PPM_MessageRecord> PPM_MessageRecord { get; set; }
        public virtual ICollection<PPM_MessageRecord> PPM_MessageRecord1 { get; set; }
        public virtual ICollection<PPM_ProjectInfo> PPM_ProjectInfo { get; set; }
        public virtual PPM_ProjectInfo PPM_ProjectInfo1 { get; set; }
        public virtual ICollection<PPM_ProjectPlan> PPM_ProjectPlan { get; set; }
        public virtual ICollection<PPM_ProjectPlan> PPM_ProjectPlan1 { get; set; }
        public virtual ICollection<PPM_ProjectTeam> PPM_ProjectTeam { get; set; }
        public virtual ICollection<PPM_ProjectTeam> PPM_ProjectTeam1 { get; set; }
        public virtual ICollection<PPM_ShareFile> PPM_ShareFile { get; set; }
        public virtual SYS_UserExt SYS_UserExt { get; set; }
        public virtual ICollection<PPM_ProblemTrace> PPM_ProblemTrace { get; set; }
        public virtual ICollection<PPM_ProblemTrace> PPM_ProblemTrace1 { get; set; }
        public virtual ICollection<PPM_ProblemTrace> PPM_ProblemTrace2 { get; set; }
        public virtual ICollection<PPM_ProblemTrace> PPM_ProblemTrace3 { get; set; }
        public virtual ICollection<PPM_ProblemTrace> PPM_ProblemTrace4 { get; set; }
        public virtual ICollection<PPM_ProblemTrace> PPM_ProblemTrace5 { get; set; }
    }
}
