//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SortDict
    {
        public SYS_SortDict()
        {
            this.PPM_ShareFile = new HashSet<PPM_ShareFile>();
        }
    
        public string SortCode { get; set; }
        public string SortName { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<PPM_ShareFile> PPM_ShareFile { get; set; }
    }
}
