//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Version
    {
        public string VersionNo { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<byte> IsDefault { get; set; }
        public string Memo { get; set; }
        public string FilePath { get; set; }
        public string FileServiceUrlPort { get; set; }
    }
}
