//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Menu
    {
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string ParentCode { get; set; }
        public int OrderCode { get; set; }
        public byte SortGrade { get; set; }
        public byte HasNext { get; set; }
        public string FormModule { get; set; }
        public string FormName { get; set; }
        public byte Status { get; set; }
    }
}
