//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAJ.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProjectPlan
    {
        public int ID { get; set; }
        public string Unit { get; set; }
        public string Activity { get; set; }
        public string BusinessCode { get; set; }
        public string Task { get; set; }
        public Nullable<decimal> BudgetWorkload { get; set; }
        public Nullable<System.DateTime> BudgetBeginDate { get; set; }
        public Nullable<System.DateTime> BudgetEndDate { get; set; }
        public Nullable<byte> DeleteFlag { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<byte> HideFlag { get; set; }
        public Nullable<decimal> RealWorkload { get; set; }
        public Nullable<System.DateTime> RealBeginDate { get; set; }
        public Nullable<System.DateTime> RealEndDate { get; set; }
        public Nullable<System.DateTime> TestPassDate { get; set; }
        public string Status { get; set; }
        public string DealPerson { get; set; }
        public string TestPerson { get; set; }
        public Nullable<int> ProblemTraceID { get; set; }
        public string DispatchStatus { get; set; }
        public string DiffAnalyze { get; set; }
    }
}
